services:
  backend:
    container_name: WordBackEnd
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - "./backend:/app"
    depends_on:
      - pg
  front_end:
    container_name: WordFrontEnd
    environment:
      WATCHPACK_POLLING: "true"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "node_modules:/app/node_modules"
  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"

volumes:
  node_modules: